Prevent order_by in union arguments, #83
Due to the table-qualification of columns allowing order by in union
arguments would result in invalid SQL, e.g.

```
sqlpp_postgresql=> select id from tab_bar
                   union all
                   select id from tab_foo order by tab_foo.id desc;
ERROR:  missing FROM-clause entry for table "tab_foo"
LINE 1: ...tab_bar union all select id from tab_foo order by tab_foo.id...
                                                             ^
```

The reason is that the order by after the rhs union argument is applied
to the whole union. It would be valid SQL without the
table-qualification.